--  ________________________________________________________________________
-- / Copyright (c) 2026 Phobos A. D'thorga                                \
-- |                                                                        |
-- |           /\_/\                                                         |
-- |         =/ o o \=    Phobos' PZ Modding                                |
-- |          (  V  )     All rights reserved.                              |
-- |     /\  / \   / \                                                      |
-- |    /  \/   '-'   \   This source code is part of the Phobos            |
-- |   /  /  \  ^  /\  \  mod suite for Project Zomboid (Build 42).         |
-- |  (__/    \_/ \/  \__)                                                  |
-- |     |   | |  | |     Unauthorised copying, modification, or            |
-- |     |___|_|  |_|     distribution of this file is prohibited.          |
-- |                                                                        |
-- \________________________________________________________________________/
--

---------------------------------------------------------------
-- POS_Screen_BBSRumours.lua
-- BBS Rumours screen for the POSnet terminal.
-- Displays active market rumours generated by the Living
-- Market system. Each entry shows the event message, region,
-- affected categories, impact hint, and days remaining.
---------------------------------------------------------------

require "PhobosLib"
require "POS_Constants"
require "POS_ScreenManager"
require "POS_TerminalWidgets"
require "PhobosLib_Pagination"
require "POS_API"

---------------------------------------------------------------

local _TAG = "[POS:BBSRumours]"

local screen = {}
screen.id = POS_Constants.SCREEN_BBS_RUMOURS
screen.menuPath = {"pos.bbs"}
screen.titleKey = "UI_POS_BBS_MarketRumours"
screen.sortOrder = 30

function screen.create(contentPanel, _params, _terminal)
    local W = POS_TerminalWidgets
    local C = W.COLOURS
    local ctx = W.initLayout(contentPanel)

    -- Header
    W.drawHeader(ctx, "UI_POS_BBS_MarketRumours")

    -- Fetch active rumours (nil-safe — POS_RumourGenerator may not exist yet)
    local currentDay = getGameTime():getNightsSurvived()
    local rumours = {}
    if POS_RumourGenerator and POS_RumourGenerator.getActiveRumours then
        rumours = POS_RumourGenerator.getActiveRumours(currentDay) or {}
    end

    if #rumours == 0 then
        W.createLabel(ctx.panel, 8, ctx.y,
            W.safeGetText("UI_POS_BBS_NoRumours"), C.dim)
        ctx.y = ctx.y + ctx.lineH
    else
        local currentPage = (_params and _params.rumoursPage) or 1
        ctx.y = PhobosLib_Pagination.create(ctx.panel, {
            items = rumours,
            pageSize = POS_Constants.PAGE_SIZE_BBS_RUMOURS,
            currentPage = currentPage,
            x = ctx.btnX,
            y = ctx.y,
            width = ctx.btnW,
            colours = {
                text = C.text, dim = C.dim,
                bgDark = C.bgDark, bgHover = C.bgHover,
                border = C.border,
            },
            renderItem = function(parent, rx, ry, rw, rumour, _idx)
                local itemY = 0

                -- Line 1: Event message (translated)
                local messageKey = rumour.messageKey or "UI_POS_BBS_UnknownRumour"
                local message = W.safeGetText(messageKey)
                W.createLabel(parent, rx, ry + itemY, message, C.text)
                itemY = itemY + ctx.lineH

                -- Line 2: Region + affected categories (dimmed)
                local region = rumour.region or "???"
                local categories = rumour.categories or "???"
                local detailLine = region .. " — " .. categories
                W.createLabel(parent, rx + 8, ry + itemY, detailLine, C.dim)
                itemY = itemY + ctx.lineH

                -- Line 3: Impact hint + days remaining (dimmed)
                local impact = rumour.impactHint or "?"
                local expiryDay = rumour.expiryDay or currentDay
                local daysLeft = expiryDay - currentDay
                if daysLeft < 0 then daysLeft = 0 end
                local metaLine = W.safeGetText("UI_POS_BBS_RumourImpact") .. ": "
                    .. impact .. "  |  "
                    .. W.safeGetText("UI_POS_BBS_RumourDaysLeft", tostring(daysLeft))
                W.createLabel(parent, rx + 8, ry + itemY, metaLine, C.dim)
                itemY = itemY + ctx.lineH

                return itemY + 4
            end,
            onPageChange = function(newPage)
                POS_ScreenManager.replaceCurrent(POS_Constants.SCREEN_BBS_RUMOURS,
                    { rumoursPage = newPage })
            end,
        })
    end

    -- Footer
    W.drawFooter(ctx)
end

screen.getContextData = function(_params)
    local data = {}
    local currentDay = getGameTime():getNightsSurvived()
    local count = 0
    if POS_RumourGenerator and POS_RumourGenerator.getRumourCount then
        count = PhobosLib.safecall(POS_RumourGenerator.getRumourCount, currentDay) or 0
    end
    if count > 0 then
        table.insert(data, { type = "kv", key = "UI_POS_BBS_RumourCount", value = tostring(count) })
    end
    return data
end

screen.destroy = POS_TerminalWidgets.defaultDestroy

function screen.refresh(params)
    POS_TerminalWidgets.dynamicRefresh(screen, params)
end

---------------------------------------------------------------

POS_API.registerScreen(screen)
