--  ________________________________________________________________________
-- / Copyright (c) 2026 Phobos A. D'thorga                                \
-- |                                                                        |
-- |           /\_/\                                                         |
-- |         =/ o o \=    Phobos' PZ Modding                                |
-- |          (  V  )     All rights reserved.                              |
-- |     /\  / \   / \                                                      |
-- |    /  \/   '-'   \   This source code is part of the Phobos            |
-- |   /  /  \  ^  /\  \  mod suite for Project Zomboid (Build 42).         |
-- |  (__/    \_/ \/  \__)                                                  |
-- |     |   | |  | |     Unauthorised copying, modification, or            |
-- |     |___|_|  |_|     distribution of this file is prohibited.          |
-- |                                                                        |
-- \________________________________________________________________________/
--

---------------------------------------------------------------
-- POS_Screen_EventLog.lua
-- Paginated market event log. Displays recent economic events
-- generated by the Living Market simulation. Each entry shows
-- day, event type, affected zone, categories, and signal class.
---------------------------------------------------------------

require "PhobosLib"
require "POS_Constants"
require "POS_ScreenManager"
require "POS_TerminalWidgets"
require "POS_WorldState"
require "PhobosLib_Pagination"
require "POS_API"

---------------------------------------------------------------

local screen = {}
screen.id = POS_Constants.SCREEN_EVENT_LOG
screen.menuPath = {"pos.markets"}
screen.titleKey = "UI_POS_EventLog_Title"
screen.sortOrder = 25

--- Get the colour for a signal class.
---@param signalClass string  "Hard", "Soft", or "Structural"
---@param C table             COLOURS table from TerminalWidgets
---@return table              RGBA colour
local function _getSignalColour(signalClass, C)
    if signalClass == "Hard" then
        return C.warning or {0.9, 0.7, 0.2, 1}
    elseif signalClass == "Soft" then
        return {0.2, 0.8, 0.7, 1}
    elseif signalClass == "Structural" then
        return C.error or {0.8, 0.3, 0.3, 1}
    end
    return C.dim or {0.6, 0.6, 0.6, 1}
end

--- Get the translation key for a signal class.
---@param signalClass string  "Hard", "Soft", or "Structural"
---@return string             Translation key
local function _getSignalKey(signalClass)
    if signalClass == "Hard" then
        return "UI_POS_EventLog_SignalHard"
    elseif signalClass == "Soft" then
        return "UI_POS_EventLog_SignalSoft"
    elseif signalClass == "Structural" then
        return "UI_POS_EventLog_SignalStructural"
    end
    return "UI_POS_EventLog_SignalSoft"
end

function screen.create(contentPanel, _params, _terminal)
    local W = POS_TerminalWidgets
    local C = W.COLOURS
    local ctx = W.initLayout(contentPanel)

    -- Header
    W.drawHeader(ctx, "UI_POS_EventLog_Title")

    -- Fetch recent events (nil-safe)
    local world = POS_WorldState.getWorld()
    local events = (world and world.recentEvents) or {}

    -- Convert to array if stored as table with string keys
    local eventList = {}
    if type(events) == "table" then
        for k, v in pairs(events) do
            if type(v) == "table" then
                table.insert(eventList, v)
            end
        end
    end

    -- Sort by day descending (newest first)
    table.sort(eventList, function(a, b)
        return (a.day or 0) > (b.day or 0)
    end)

    if #eventList == 0 then
        W.createLabel(ctx.panel, 8, ctx.y,
            W.safeGetText("UI_POS_EventLog_NoEvents"), C.dim)
        ctx.y = ctx.y + ctx.lineH
    else
        local currentPage = (_params and _params.eventPage) or 1
        ctx.y = PhobosLib_Pagination.create(ctx.panel, {
            items = eventList,
            pageSize = POS_Constants.PAGE_SIZE_EVENT_LOG,
            currentPage = currentPage,
            x = ctx.btnX,
            y = ctx.y,
            width = ctx.btnW,
            colours = {
                text = C.text, dim = C.dim,
                bgDark = C.bgDark, bgHover = C.bgHover,
                border = C.border,
            },
            renderItem = function(parent, rx, ry, rw, event, _idx)
                local itemY = 0

                -- Line 1: "Day X — <event type translated>"
                local dayStr = W.safeGetText("UI_POS_EventLog_Day",
                    tostring(event.day or 0))
                local eventTypeKey = event.typeKey or event.type or "???"
                local eventType = W.safeGetText(eventTypeKey)
                W.createLabel(parent, rx, ry + itemY,
                    dayStr .. " — " .. eventType, C.text)
                itemY = itemY + ctx.lineH

                -- Line 2: "  Zone: <zone> | Categories: <cats> | <signal class>"
                local zone = event.zoneId or event.zone or "???"
                local cats = event.categories
                if type(cats) == "table" then
                    cats = table.concat(cats, ", ")
                end
                cats = cats or "???"
                local signalClass = event.signalClass or "Soft"
                local signalKey = _getSignalKey(signalClass)
                local signalColour = _getSignalColour(signalClass, C)

                local detailLine = "  Zone: " .. zone
                    .. " | " .. W.safeGetText("UI_POS_EventLog_Categories", cats)
                    .. " | " .. W.safeGetText(signalKey)
                W.createLabel(parent, rx, ry + itemY, detailLine, signalColour)
                itemY = itemY + ctx.lineH

                return itemY + 4
            end,
            onPageChange = function(newPage)
                POS_ScreenManager.replaceCurrent(POS_Constants.SCREEN_EVENT_LOG,
                    { eventPage = newPage })
            end,
        })
    end

    -- Footer
    W.drawFooter(ctx)
end

screen.getContextData = function(_params)
    local data = {}
    local world = POS_WorldState.getWorld()
    local events = (world and world.recentEvents) or {}
    local count = 0
    for _ in pairs(events) do
        count = count + 1
    end
    if count > 0 then
        table.insert(data, { type = "kv", key = "UI_POS_EventLog_Title",
            value = tostring(count) })
    end
    return data
end

screen.destroy = POS_TerminalWidgets.defaultDestroy

function screen.refresh(params)
    POS_TerminalWidgets.dynamicRefresh(screen, params)
end

---------------------------------------------------------------

POS_API.registerScreen(screen)
