return {
    schemaVersion = 1,
    id = "voice_crafter",
    archetypeId = "specialist_crafter",
    description = "Technical, workshop-focused, precision language",
    overrides = {
        situation  = "voice_crafter_situations",
        submission = "voice_crafter_submissions",
        investment = "voice_crafter_investments",
        wbn_opener = "voice_wbn_crafter_openers",
        wbn_closer = "voice_wbn_crafter_closers",
        wbn_ops_agent_transit       = "voice_wbn_ops_agent_transit",
        wbn_ops_agent_delayed       = "voice_wbn_ops_agent_delayed",
        wbn_ops_agent_compromised   = "voice_wbn_ops_agent_compromised",
        wbn_ops_agent_completed     = "voice_wbn_ops_agent_completed",
        wbn_ops_mission_success     = "voice_wbn_ops_mission_success",
        wbn_ops_mission_failure     = "voice_wbn_ops_mission_failure",
        wbn_ops_wholesaler_posture  = "voice_wbn_ops_wholesaler_posture",
        wbn_ops_generic             = "voice_wbn_ops_generic",
    },
}
