return {
    schemaVersion = 1,
    id = "voice_field_reporter",
    archetypeId = "field_reporter",
    description = "Urgent, concise, emergency-focused broadcast voice",
    overrides = {
        wbn_opener             = "voice_wbn_field_reporter_openers",
        wbn_closer             = "voice_wbn_field_reporter_closers",
        wbn_weather            = "voice_wbn_field_reporter_weather",
        wbn_power              = "voice_wbn_field_reporter_power",
        wbn_flavour_market     = "voice_wbn_field_reporter_flavour_market",
        wbn_flavour_emergency  = "voice_wbn_field_reporter_flavour_emergency",
        wbn_ops_agent_transit       = "voice_wbn_ops_agent_transit",
        wbn_ops_agent_delayed       = "voice_wbn_ops_agent_delayed",
        wbn_ops_agent_compromised   = "voice_wbn_ops_agent_compromised",
        wbn_ops_agent_completed     = "voice_wbn_ops_agent_completed",
        wbn_ops_mission_success     = "voice_wbn_ops_mission_success",
        wbn_ops_mission_failure     = "voice_wbn_ops_mission_failure",
        wbn_ops_wholesaler_posture  = "voice_wbn_ops_wholesaler_posture",
        wbn_ops_generic             = "voice_wbn_ops_generic",
    },
}
