return {
    schemaVersion = 1,
    id = "voice_quartermaster",
    archetypeId = "quartermaster",
    description = "Methodical, logistics-focused, supply-chain language",
    overrides = {
        situation  = "voice_quartermaster_situations",
        submission = "voice_quartermaster_submissions",
        investment = "voice_quartermaster_investments",
        wbn_opener             = "voice_wbn_quartermaster_openers",
        wbn_closer             = "voice_wbn_quartermaster_closers",
        wbn_weather            = "voice_wbn_quartermaster_weather",
        wbn_power              = "voice_wbn_quartermaster_power",
        wbn_flavour_market     = "voice_wbn_quartermaster_flavour_market",
        wbn_flavour_emergency  = "voice_wbn_quartermaster_flavour_emergency",
        wbn_ops_agent_transit       = "voice_wbn_ops_agent_transit",
        wbn_ops_agent_delayed       = "voice_wbn_ops_agent_delayed",
        wbn_ops_agent_compromised   = "voice_wbn_ops_agent_compromised",
        wbn_ops_agent_completed     = "voice_wbn_ops_agent_completed",
        wbn_ops_mission_success     = "voice_wbn_ops_mission_success",
        wbn_ops_mission_failure     = "voice_wbn_ops_mission_failure",
        wbn_ops_wholesaler_posture  = "voice_wbn_ops_wholesaler_posture",
        wbn_ops_generic             = "voice_wbn_ops_generic",
    },
}
