return {
    schemaVersion = 1,
    id = "voice_scavenger",
    archetypeId = "scavenger_trader",
    description = "Scrappy, desperate, survival-focused language",
    overrides = {
        situation  = "voice_scavenger_situations",
        submission = "voice_scavenger_submissions",
        investment = "voice_scavenger_investments",
        wbn_opener             = "voice_wbn_scavenger_openers",
        wbn_closer             = "voice_wbn_scavenger_closers",
        wbn_weather            = "voice_wbn_scavenger_weather",
        wbn_power              = "voice_wbn_scavenger_power",
        wbn_flavour_market     = "voice_wbn_scavenger_flavour_market",
        wbn_flavour_emergency  = "voice_wbn_scavenger_flavour_emergency",
        wbn_ops_agent_transit       = "voice_wbn_ops_agent_transit",
        wbn_ops_agent_delayed       = "voice_wbn_ops_agent_delayed",
        wbn_ops_agent_compromised   = "voice_wbn_ops_agent_compromised",
        wbn_ops_agent_completed     = "voice_wbn_ops_agent_completed",
        wbn_ops_mission_success     = "voice_wbn_ops_mission_success",
        wbn_ops_mission_failure     = "voice_wbn_ops_mission_failure",
        wbn_ops_wholesaler_posture  = "voice_wbn_ops_wholesaler_posture",
        wbn_ops_generic             = "voice_wbn_ops_generic",
    },
}
