return {
    schemaVersion = 1,
    id = "voice_smuggler",
    archetypeId = "smuggler",
    description = "Shadowy, informal, off-the-books language",
    overrides = {
        situation  = "voice_smuggler_situations",
        submission = "voice_smuggler_submissions",
        agentState = "voice_smuggler_agent_states",
        investment = "voice_smuggler_investments",
        wbn_opener             = "voice_wbn_smuggler_openers",
        wbn_closer             = "voice_wbn_smuggler_closers",
        wbn_weather            = "voice_wbn_smuggler_weather",
        wbn_power              = "voice_wbn_smuggler_power",
        wbn_flavour_market     = "voice_wbn_smuggler_flavour_market",
        wbn_flavour_emergency  = "voice_wbn_smuggler_flavour_emergency",
        wbn_ops_agent_transit       = "voice_wbn_ops_agent_transit",
        wbn_ops_agent_delayed       = "voice_wbn_ops_agent_delayed",
        wbn_ops_agent_compromised   = "voice_wbn_ops_agent_compromised",
        wbn_ops_agent_completed     = "voice_wbn_ops_agent_completed",
        wbn_ops_mission_success     = "voice_wbn_ops_mission_success",
        wbn_ops_mission_failure     = "voice_wbn_ops_mission_failure",
        wbn_ops_wholesaler_posture  = "voice_wbn_ops_wholesaler_posture",
        wbn_ops_generic             = "voice_wbn_ops_generic",
    },
}
