return {
    schemaVersion = 1,
    id = "voice_trader",
    archetypeId = "baseline_trader",
    description = "Mercantile, profit-focused, business language",
    overrides = {
        situation  = "voice_trader_situations",
        submission = "voice_trader_submissions",
        agentState = "voice_trader_agent_states",
        investment = "voice_trader_investments",
        wbn_opener             = "voice_wbn_trader_openers",
        wbn_closer             = "voice_wbn_trader_closers",
        wbn_weather            = "voice_wbn_trader_weather",
        wbn_power              = "voice_wbn_trader_power",
        wbn_flavour_market     = "voice_wbn_trader_flavour_market",
        wbn_flavour_emergency  = "voice_wbn_trader_flavour_emergency",
        wbn_ops_agent_transit       = "voice_wbn_ops_agent_transit",
        wbn_ops_agent_delayed       = "voice_wbn_ops_agent_delayed",
        wbn_ops_agent_compromised   = "voice_wbn_ops_agent_compromised",
        wbn_ops_agent_completed     = "voice_wbn_ops_agent_completed",
        wbn_ops_mission_success     = "voice_wbn_ops_mission_success",
        wbn_ops_mission_failure     = "voice_wbn_ops_mission_failure",
        wbn_ops_wholesaler_posture  = "voice_wbn_ops_wholesaler_posture",
        wbn_ops_generic             = "voice_wbn_ops_generic",
    },
}
