return {
    schemaVersion = 1,
    id = "sigint_deep_scan",
    name = "Deep Frequency Scan",
    description = "Extended monitoring across multiple frequency bands.",
    category = "sigint",
    difficultyMin = 4,
    difficultyMax = 5,
    briefingPools = {
        title      = "titles_common",
        situation  = "situations_common",
        tasking    = "taskings_common",
        constraints = "constraints_common",
        submission = "submissions_common",
    },
    objectives = {
        { type = "monitor",   description = "Establish monitoring on primary frequency" },
        { type = "monitor",   description = "Scan secondary frequency band" },
        { type = "intercept", description = "Log all intercepted transmissions" },
        { type = "analyse",   description = "Cross-reference captured traffic" },
        { type = "report",    description = "Submit analysis via terminal" },
    },
    rewardMin = 200,
    rewardMax = 600,
    reputationMin = 15,
    reputationMax = 35,
    expiryDaysMin = 3,
    expiryDaysMax = 5,
}
